version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-225-242-183.compute-1.amazonaws.com
            database: d6rhc69tdgtl3t
            user: dntxlotqhupumb
            password: 45cd8525b4962ca9cffb9a454f97682dc6ff57c183147bae952936e054acedbb
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true